server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: clientservice
          uri: lb://clientservice
          predicates:
            - Path=/clients/**
        - id:  loanservice
          uri: lb://loanservice
          predicates:
            - Path=/loan/**