server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: ExamenFinal
          uri: https://github.com/A-caro/Aprendizaje.git
          search-paths: config-data

  application:
    name: config-service

